/* Generated By:JJTree: Do not edit this line. ASTbreak_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbreak_ extends SimpleNode {
  public ASTbreak_(int id) {
    super(id);
  }

  public ASTbreak_(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=438295fc7760193812e94e53467c9e45 (do not edit this line) */
