/* Generated By:JJTree: Do not edit this line. ASTclass_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclass_list extends SimpleNode {
  public ASTclass_list(int id) {
    super(id);
  }

  public ASTclass_list(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2f52a4e4e9774cc9d14a55212d100d89 (do not edit this line) */
