/* Generated By:JJTree: Do not edit this line. ASTclass_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclass_ extends SimpleNode {
  public ASTclass_(int id) {
    super(id);
  }

  public ASTclass_(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b09c1170aaf9ac05a7232b6ce31af46e (do not edit this line) */
