/* Generated By:JJTree: Do not edit this line. ASTclass_def.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclass_def extends SimpleNode {
  public ASTclass_def(int id) {
    super(id);
  }

  public ASTclass_def(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=89494d122494a0a90679d4769a884376 (do not edit this line) */
