/* Generated By:JJTree: Do not edit this line. ASTclass_call.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclass_call extends SimpleNode {
  public ASTclass_call(int id) {
    super(id);
  }

  public ASTclass_call(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e0523fa8251672441f14a35b85c2d2e (do not edit this line) */
