/* Generated By:JJTree: Do not edit this line. ASTconst_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconst_decl extends SimpleNode {
  public ASTconst_decl(int id) {
    super(id);
  }

  public ASTconst_decl(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=61b83b94c21dc6c81a6eba3813251c24 (do not edit this line) */
