/* Generated By:JJTree: Do not edit this line. ASTconditionPrime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconditionPrime extends SimpleNode {
  public ASTconditionPrime(int id) {
    super(id);
  }

  public ASTconditionPrime(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fb98cba0dc8bf2f9d7b7262d62a10423 (do not edit this line) */
