/* Generated By:JJTree: Do not edit this line. ASTd_structure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTd_structure extends SimpleNode {
  public ASTd_structure(int id) {
    super(id);
  }

  public ASTd_structure(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b0bb1f22b2165ae5ed0f8d3c90b90c99 (do not edit this line) */
