/* Generated By:JJTree: Do not edit this line. ASTdecl_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdecl_list extends SimpleNode {
  public ASTdecl_list(int id) {
    super(id);
  }

  public ASTdecl_list(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0d48319eda1e524136b05b1c64d0bf9 (do not edit this line) */
