/* Generated By:JJTree: Do not edit this line. ASTdictionary.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdictionary extends SimpleNode {
  public ASTdictionary(int id) {
    super(id);
  }

  public ASTdictionary(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8f9e3b3d7bb13bfb2893ba2ec433693a (do not edit this line) */
