/* Generated By:JJTree: Do not edit this line. ASTelse_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTelse_ extends SimpleNode {
  public ASTelse_(int id) {
    super(id);
  }

  public ASTelse_(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cf00de0c0ab4e2a8456aa8788f2b2729 (do not edit this line) */
