/* Generated By:JJTree: Do not edit this line. ASTelse_if_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTelse_if_list extends SimpleNode {
  public ASTelse_if_list(int id) {
    super(id);
  }

  public ASTelse_if_list(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=68c4c9566b0f14035e28c2d14da4ae3e (do not edit this line) */
