/* Generated By:JJTree: Do not edit this line. ASTElseIF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseIF extends SimpleNode {
  public ASTElseIF(int id) {
    super(id);
  }

  public ASTElseIF(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a6f2d21b7e8ecf7c02b3c246ad10adc (do not edit this line) */
