/* Generated By:JJTree: Do not edit this line. ASTfunction_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunction_list extends SimpleNode {
  public ASTfunction_list(int id) {
    super(id);
  }

  public ASTfunction_list(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=87cc554bd1308a2b77fc1d852f70eb3b (do not edit this line) */
