/* Generated By:JJTree: Do not edit this line. ASTfragmentPrime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfragmentPrime extends SimpleNode {
  public ASTfragmentPrime(int id) {
    super(id);
  }

  public ASTfragmentPrime(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8cb6e20bd74918da0d404036782b0804 (do not edit this line) */
