/* Generated By:JJTree: Do not edit this line. ASTgetStringLength.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgetStringLength extends SimpleNode {
  public ASTgetStringLength(int id) {
    super(id);
  }

  public ASTgetStringLength(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ef99bec77ddb1fa199c60a2a7796aec (do not edit this line) */
