/* Generated By:JJTree: Do not edit this line. ASTgetArray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgetArray extends SimpleNode {
  public ASTgetArray(int id) {
    super(id);
  }

  public ASTgetArray(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=36abd759ff0a64e657c48a2070e6556e (do not edit this line) */
