/* Generated By:JJTree: Do not edit this line. ASTgetChar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgetChar extends SimpleNode {
  public ASTgetChar(int id) {
    super(id);
  }

  public ASTgetChar(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=944640445972bba9af2ceb94b47e74d0 (do not edit this line) */
