/* Generated By:JJTree: Do not edit this line. ASTinsert.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinsert extends SimpleNode {
  public ASTinsert(int id) {
    super(id);
  }

  public ASTinsert(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=15ff80b8c7e1c37ee4fe79036aee2557 (do not edit this line) */
