/* Generated By:JJTree: Do not edit this line. ASTnemp_parameter_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnemp_parameter_list extends SimpleNode {
  public ASTnemp_parameter_list(int id) {
    super(id);
  }

  public ASTnemp_parameter_list(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=11cb3ce4d43f440800a21ab3c0cbbf13 (do not edit this line) */
