/* Generated By:JJTree: Do not edit this line. ASTreturn_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturn_ extends SimpleNode {
  public ASTreturn_(int id) {
    super(id);
  }

  public ASTreturn_(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d8b9be44cc4cd0aa496f3fc4ddd5331 (do not edit this line) */
