/* Generated By:JJTree: Do not edit this line. ASTstatement_Left_factor_IDENTIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement_Left_factor_IDENTIFIER extends SimpleNode {
  public ASTstatement_Left_factor_IDENTIFIER(int id) {
    super(id);
  }

  public ASTstatement_Left_factor_IDENTIFIER(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b1988dba49be3489fcbe318e62ee064a (do not edit this line) */
