/* Generated By:JJTree: Do not edit this line. ASTvalues.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvalues extends SimpleNode {
  public ASTvalues(int id) {
    super(id);
  }

  public ASTvalues(mona p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(monaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6c9a7e11e6ebc772f47338a70ad58eb7 (do not edit this line) */
