/* Generated By:JavaCC: Do not edit this line. monaTreeConstants.java Version 5.0 */
public interface monaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARIABLEDECLARATION = 2;
  public int JJTASSIGNS = 3;
  public int JJTCONSTANTDECLARATION = 4;
  public int JJTFUNCTION = 5;
  public int JJTRETURN_ = 6;
  public int JJTTYPE = 7;
  public int JJTPARAMETER_LIST = 8;
  public int JJTMAIN = 9;
  public int JJTSTATEMENT = 10;
  public int JJTELSE_ = 11;
  public int JJTASSIGNMENT = 12;
  public int JJTFUNCTIONCALL = 13;
  public int JJTCLASS_CALL = 14;
  public int JJTARITH_OP = 15;
  public int JJTCOMP_OP = 16;
  public int JJTANDCONDITION = 17;
  public int JJTORCONDITION = 18;
  public int JJTARGUMENTLIST = 19;
  public int JJTARRAY = 20;
  public int JJTCLASS_ = 21;
  public int JJTDECL_LIST = 22;
  public int JJTIDENTIFIER = 23;
  public int JJTBREAK_ = 24;
  public int JJTNUMBER = 25;
  public int JJTSTRING = 26;
  public int JJTBOOLEAN = 27;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VariableDeclaration",
    "assigns",
    "ConstantDeclaration",
    "function",
    "return_",
    "Type",
    "parameter_list",
    "main",
    "statement",
    "else_",
    "assignment",
    "functionCall",
    "class_call",
    "arith_op",
    "comp_op",
    "andCondition",
    "orCondition",
    "argumentList",
    "array",
    "class_",
    "decl_list",
    "Identifier",
    "break_",
    "Number",
    "String",
    "Boolean",
  };
}
/* JavaCC - OriginalChecksum=6bd4dc118f44b58f86f2e1eade6c2ef9 (do not edit this line) */
