/* Generated By:JavaCC: Do not edit this line. monaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface monaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int CONST = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int VOID = 17;
  /** RegularExpression Id. */
  int MAIN = 18;
  /** RegularExpression Id. */
  int BREAK = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int ELSEIF = 22;
  /** RegularExpression Id. */
  int EXCEPT = 23;
  /** RegularExpression Id. */
  int NOT = 24;
  /** RegularExpression Id. */
  int print = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int FOR = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int SKIP_mona = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int SEMIC = 34;
  /** RegularExpression Id. */
  int COLON = 35;
  /** RegularExpression Id. */
  int LCBR = 36;
  /** RegularExpression Id. */
  int RCBR = 37;
  /** RegularExpression Id. */
  int LBR = 38;
  /** RegularExpression Id. */
  int RBR = 39;
  /** RegularExpression Id. */
  int LSBR = 40;
  /** RegularExpression Id. */
  int RSBR = 41;
  /** RegularExpression Id. */
  int ASSIGN = 42;
  /** RegularExpression Id. */
  int PLUS_SIGN = 43;
  /** RegularExpression Id. */
  int MINUS_SIGN = 44;
  /** RegularExpression Id. */
  int LOG_NEG = 45;
  /** RegularExpression Id. */
  int OR = 46;
  /** RegularExpression Id. */
  int AND = 47;
  /** RegularExpression Id. */
  int EQUAL = 48;
  /** RegularExpression Id. */
  int NOT_EQUAL = 49;
  /** RegularExpression Id. */
  int LESS_THAN = 50;
  /** RegularExpression Id. */
  int LESS_THAN_OR_EQUAL = 51;
  /** RegularExpression Id. */
  int GREATER_THAN = 52;
  /** RegularExpression Id. */
  int GREATER_THAN_OR_EQUAL = 53;
  /** RegularExpression Id. */
  int DIGIT = 54;
  /** RegularExpression Id. */
  int CHAR = 55;
  /** RegularExpression Id. */
  int NUM = 56;
  /** RegularExpression Id. */
  int FLOAT = 57;
  /** RegularExpression Id. */
  int IDENTIFIER = 58;
  /** RegularExpression Id. */
  int QUOTED_STRING = 59;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"var\"",
    "\"const\"",
    "\"return\"",
    "\"class\"",
    "\"int\"",
    "\"bool\"",
    "\"void\"",
    "\"main\"",
    "\"break\"",
    "\"if\"",
    "\"else\"",
    "\"else_if\"",
    "\"except\"",
    "\"not\"",
    "\"print\"",
    "\"in\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"for\"",
    "\"string\"",
    "\"skip\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<DIGIT>",
    "<CHAR>",
    "<NUM>",
    "<FLOAT>",
    "<IDENTIFIER>",
    "<QUOTED_STRING>",
  };

}
