/* Generated By:JavaCC: Do not edit this line. monaTreeConstants.java Version 5.0 */
public interface monaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARIABLEDECLARATION = 2;
  public int JJTASSIGNS = 3;
  public int JJTCONSTANTDECLARATION = 4;
  public int JJTFUNCTION = 5;
  public int JJTRETURN_ = 6;
  public int JJTTYPE = 7;
  public int JJTPARAMETER_LIST = 8;
  public int JJTMAIN = 9;
  public int JJTSTATEMENT = 10;
  public int JJTELSE_IF = 11;
  public int JJTFUNCTIONCALL = 12;
  public int JJTINSERT = 13;
  public int JJTARITH_OP = 14;
  public int JJTGETARRAY = 15;
  public int JJTGETLENGTH = 16;
  public int JJTGETSTRINGLENGTH = 17;
  public int JJTGETCHAR = 18;
  public int JJTCOMP_OP = 19;
  public int JJTANDCONDITION = 20;
  public int JJTORCONDITION = 21;
  public int JJTARGUMENTLIST = 22;
  public int JJTARRAY = 23;
  public int JJTCLASS_ = 24;
  public int JJTDECL_LIST = 25;
  public int JJTIDENTIFIER = 26;
  public int JJTBREAK_ = 27;
  public int JJTNUMBER = 28;
  public int JJTFLOAT = 29;
  public int JJTSTRING = 30;
  public int JJTBOOLEAN = 31;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VariableDeclaration",
    "assigns",
    "ConstantDeclaration",
    "function",
    "return_",
    "Type",
    "parameter_list",
    "main",
    "statement",
    "else_if",
    "functionCall",
    "insert",
    "arith_op",
    "getArray",
    "getLength",
    "getStringLength",
    "getChar",
    "comp_op",
    "andCondition",
    "orCondition",
    "argumentList",
    "array",
    "class_",
    "decl_list",
    "Identifier",
    "break_",
    "Number",
    "Float",
    "String",
    "Boolean",
  };
}
/* JavaCC - OriginalChecksum=75064712c8b4e9b807f1c6f6ab32a21a (do not edit this line) */
