/* Generated By:JavaCC: Do not edit this line. monaVisitor.java Version 5.0 */
public interface monaVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVariableDeclaration node, Object data);
  public Object visit(ASTassigns node, Object data);
  public Object visit(ASTConstantDeclaration node, Object data);
  public Object visit(ASTfunction node, Object data);
  public Object visit(ASTreturn_ node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTparameter_list node, Object data);
  public Object visit(ASTmain node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTelse_if node, Object data);
  public Object visit(ASTfunctionCall node, Object data);
  public Object visit(ASTclass_call node, Object data);
  public Object visit(ASTarith_op node, Object data);
  public Object visit(ASTcomp_op node, Object data);
  public Object visit(ASTandCondition node, Object data);
  public Object visit(ASTorCondition node, Object data);
  public Object visit(ASTargumentList node, Object data);
  public Object visit(ASTarray node, Object data);
  public Object visit(ASTclass_ node, Object data);
  public Object visit(ASTdecl_list node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTbreak_ node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTBoolean node, Object data);
}
/* JavaCC - OriginalChecksum=743aeaf0509ff4bfc04f73a79140e14c (do not edit this line) */
